repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx
        args:
          - prettier
          - --write
          - "**/*.{js,jsx,json,md}"
        language: node
        types: [javascript, json, markdown]
        pass_filenames: true
        require_serial: true

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: ["--line-length", "79", "."]
        language: system
        types: [python]
        pass_filenames: false
        files: backend/
        exclude: migrations/, staticfiles/, venv/, .*\.pyc$, .*\.pyo$, .*\.egg-info/
