# Generated by Django 4.2.2 on 2023-06-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
