# Generated by Django 4.2.2 on 2023-06-18 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subject", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            6,
                            18,
                            15,
                            38,
                            38,
                            638871,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "topicImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="topicImage/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
