# Generated by Django 4.2.2 on 2023-06-20 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="content",
            field=models.TextField(default="random content"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    6,
                    20,
                    16,
                    17,
                    10,
                    627549,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
