# Generated by Django 4.2.2 on 2023-06-17 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_alter_topic_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    6,
                    17,
                    21,
                    10,
                    53,
                    746337,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
