# Generated by Django 4.2.2 on 2023-06-18 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    6,
                    18,
                    2,
                    48,
                    42,
                    780972,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
