# Generated by Django 4.2.2 on 2023-06-17 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_staff",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    6,
                    17,
                    21,
                    10,
                    53,
                    702328,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
