# Generated by Django 4.2.2 on 2023-06-17 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_is_admin_user_is_staff_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    6,
                    17,
                    21,
                    14,
                    49,
                    310545,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
